Retkiloki/config/routes.rb
Rails.application.routes.draw do
  resources :home
  root 'home#show'
  resources :venues

  resources :types

  resources :age_groups

  resources :attendances

  resources :events

  resources :users

  get 'userlist', to:'users#list'

end

Retkiloki/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
        <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
	<li class="navbar-brand"><%= link_to 'Retkiloki', "/" %></li>
    </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	<ul class="nav navbar-nav">
	
	<li><%= link_to 'User', users_path %></li>
	<li><%= link_to 'Events', events_path %> </li>
	<li><%= link_to 'Age groups', age_groups_path %> </li>
	<li><%= link_to 'Attendances', attendances_path%> </li>
	<li><%= link_to 'Types', types_path%> </li>	
          
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <title>Retkiloki</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>